name: climaax_storms

channels:
    - conda-forge

dependencies:
        - cartopy
        - cfgrib
        - contextily
        - earthkit-data
        - eccodes
        - gdal
        - geopandas
        - ipympl
        - ipywidgets
        - jupyterlab
        - leafmap
        - matplotlib
        - nbmake
        - numpy
        - osmnx
        - pandas
        - pip
        - pyproj
        - pytest
        - python=3.11
        - rasterio
        - rioxarray
        - scipy
        - tqdm
        - xarray
        - xlrd
        - pip:
            - cdsapi
            - damagescanner
            - jupyterlab_myst
            - netcdf4
   
          
