name: climaax_storms

channels:
    - conda-forge

dependencies:
    - python=3.11
    - pip
    - jupyterlab=4.2.3
    - notebook=7.2.1
    - jupyterlab-myst=2.4.2
    - ipykernel=6.29.5
    - cdsapi=0.7.0
    - pooch=1.8.2
    - numpy=1.26.4
    - pandas=2.2.2
    - xarray=2024.6.0
    - dask=2024.7.0
    - rioxarray=0.15.7
    - rasterio=1.3.10
    - geopandas=1.0.1
    - pyogrio=0.8.0
    - shapely=2.0.4
    - contextily=1.6.0
    - matplotlib=3.8.4
    - netcdf4=1.7.1
    - openpyxl=3.1.4
    - pip:
        - damagescanner==0.7
