name: climaax_storms

channels:
    - conda-forge
    - nodefaults

# Package versions should follow the general CLIMAAX environment
# specified in https://github.com/CLIMAAX/workflow_template
dependencies:
    - cartopy=0.23.0
    - cdsapi=0.7.5
    - contextily=1.6.0
    - dask=2024.7.0
    - geopandas=1.0.1
    - ipykernel=6.29.5
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.2.7
    - matplotlib=3.8.4
    - netcdf4=1.7.1
    - notebook=7.2.2
    - numpy=1.26.4
    - openpyxl=3.1.4
    - pandas=2.2.2
    - pip
    - pooch=1.8.2
    - pyogrio=0.8.0
    - python=3.12
    - rasterio=1.3.10
    - rioxarray=0.15.7
    - shapely=2.0.6
    - xarray=2024.6.0
    - pip:
        - damagescanner==0.7
        - earthkit-geo==0.3.0
        - earthkit-plots==0.2.8
